
GET https://accidental-utopian-tellurium.glitch.me/users


###

GET https://accidental-utopian-tellurium.glitch.me/users?login=Mather&password=I-love-c00kie$1

###

POST https://accidental-utopian-tellurium.glitch.me/users HTTP/1.1
content-type: application/json

{
    "id": 2,
    "login": "Dotter",
    "password": "I-love-c00kie$1",
    "token": "2_d3u4d983u498dud"
}

###

PATCH https://accidental-utopian-tellurium.glitch.me/users/0 HTTP/1.1
content-type: application/json

{
    "login": "Mather",
    "password": "I-love-c00kie$1",
    "token": "0_8938du3j98duu34jd"
}

###

DELETE https://accidental-utopian-tellurium.glitch.me/users/2 HTTP/1.1


###








###

GET https://accidental-utopian-tellurium.glitch.me/contacts HTTP/1.1


###

GET https://accidental-utopian-tellurium.glitch.me/contacts?token=1_11111 HTTP/1.1



###

POST https://accidental-utopian-tellurium.glitch.me/contacts HTTP/1.1
content-type: application/json

{"id":"","token":"1_11111","name":"цвцвцйв","fio":"уацуацуац","telephone":"+1 (111) 111-1111","email":"уцацуа"}

###

PATCH https://accidental-utopian-tellurium.glitch.me/contacts/xDXRF8v HTTP/1.1
content-type: application/json

{
    "id": "xDXRF8v",
    "token": "1_11111",
    "name": "Qonwotejnka",
    "fio": "qqqqqqq",
    "telephone": "+79172333435",
    "email": "Qonwotejnka@mail.com"
}

###

GET https://accidental-utopian-tellurium.glitch.me/contacts/xDXRF8v HTTP/1.1

###

DELETE https://accidental-utopian-tellurium.glitch.me/contacts/11 HTTP/1.1